-- Cascade ClickHouse schema — owned by Ingestion (write), Query (read)
-- tenant_id is the first element of the PRIMARY KEY to enable per-tenant pruning.

CREATE TABLE IF NOT EXISTS events
(
    event_id     String,          -- UUIDv7, generated by ingest service
    tenant_id    String,          -- injected by ingest; all queries MUST filter on this
    event        LowCardinality(String),
    distinct_id  String,
    timestamp    DateTime64(3, 'UTC'),
    received_at  DateTime64(3, 'UTC'),
    properties   Map(String, String)  -- string-serialised values; cast in queries
)
ENGINE = MergeTree
PARTITION BY (tenant_id, toYYYYMM(timestamp))
ORDER BY (tenant_id, event, timestamp, event_id)
TTL toDateTime(timestamp) + INTERVAL 1 YEAR
SETTINGS index_granularity = 8192;
